instance_key_name = "ec2-instance-key-name"
ssh-user          = "ec2 instance ssh user"
private_key_path  = "ec2-instance-key path"
instance-type     = "instance-type"
instance-ami      = "ami id for the instance"
region            = "region"