instance_key_name = "wp-test-instance"
ssh-user          = "centos"
private_key_path  = "/home/mathew/Downloads/wp-test-instance.pem"
instance-type     = "t3.micro"
instance-ami      = "ami-03d68f1b6fcf93e47"
region            = "ap-south-1"