instance_key_name = "wp-test-instance"
ssh-user          = "centos"
private_key_path  = "/home/mathew/Downloads/wp-test-instance.pem"
instance-type     = "t3.micro"
instance-ami      = "ami-06cf02a98a61f9f5e"
region            = "ap-south-1"